### ISSUE TITLE
Export is broken

### ISSUE THREAD

**Issue by ldidry** [ether/ep_mediawiki#15]
I tested the plugin (0.0.12) on Etherpad 1.8.7, the export hang for a long time and ends with a 404.

**Comment by JohnMcLear** [comment]
Fixed in git, am fixing lint issues then it will auto publish to npm.  This plugin is heavily neglected and someone needs to pick it up to keep it moving forwards.

**Comment by JohnMcLear** [comment]
npm should be published in a few mins

**Comment by JohnMcLear** [comment]
https://twitter.com/johnmclear/status/1347177778899255297 btw
